In [1]:
import numpy as np 
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
respons = stats.ks_2samp(sample1, sample2)

In [2]:
sample1

array([0.52392705, 0.89829361, 0.56467198, 0.81257474, 0.04604673,
       0.48822503, 0.73566978, 0.21796921, 0.98792111, 0.02542399,
       0.20169267, 0.49843425, 0.12662201, 0.40152026, 0.48375892,
       0.04956064, 0.52467635, 0.67650065, 0.23846024, 0.88245881,
       0.39080738, 0.03742343, 0.93476945, 0.61885471, 0.79125241,
       0.27048517, 0.88433131, 0.74199192, 0.12553041, 0.16314228,
       0.9285809 , 0.98344314, 0.11441322, 0.82834528, 0.34464286,
       0.90308754, 0.51732309, 0.93145928, 0.66831209, 0.1310327 ,
       0.41664986, 0.2857867 , 0.43409939, 0.26010712, 0.33884725,
       0.29188926, 0.60873782, 0.23008987, 0.39753937, 0.53912335,
       0.49734138, 0.74249534, 0.26062786, 0.27868362, 0.43819346,
       0.08965473, 0.09640497, 0.9419921 , 0.7235044 , 0.7908607 ,
       0.69513425, 0.86451991, 0.01410513, 0.91561807, 0.10543121,
       0.26260601, 0.6730059 , 0.12173988, 0.87358643, 0.73558774,
       0.58241229, 0.84291967, 0.79638394, 0.87828662, 0.23806

In [3]:
sample2

array([-1.49339974, -1.22586238, -1.70815768, -0.33573469,  0.48125407,
        1.79388117,  0.47534183, -1.64971602, -0.57361365,  0.3115551 ,
       -0.17042013, -0.58017355, -1.51203217, -1.3624838 , -1.63032918,
        0.40525328,  2.74209695,  0.14900343,  1.43581693, -0.52839301,
        1.01012996,  0.91544616,  1.42925691,  0.70612194,  0.95775953,
        0.82246569, -0.96266077,  0.53918299, -0.3107219 ,  2.20085525,
        1.85589736, -1.45172214,  0.18782364,  0.38034852, -0.61470083,
       -1.13729772, -0.77687974,  1.01668836, -0.89894971, -1.71784501,
       -1.22757193, -1.12872211,  0.50617512, -0.18297153, -1.4615584 ,
       -0.04267717, -0.3055669 ,  0.25445969,  0.71692327,  0.19574765,
        0.14984366, -0.76895808,  0.74630197, -1.52221482,  0.52280862,
        0.53052568,  0.81483618,  0.11137421, -1.07926233,  0.75467681,
       -0.41857201, -1.44002703, -0.34383418,  2.07986691, -0.53502021,
       -2.30110933,  1.07753721, -1.15663215,  0.97450622,  0.56

In [4]:
respons

KstestResult(statistic=0.5263636363636364, pvalue=8.121284614693007e-14)

In [6]:
respons.pvalue

8.121284614693007e-14

In [12]:
round(respons.pvalue,20)

8.121285e-14

In [7]:
#Anamoly in my dataset
#
# 1. High Null Value
# 2. Missing column
# 3. Outlier
# 4. Categorical:
#    Gender--> MALE,FEMALE,OTHER


In [1]:
import pandas as pd 

In [2]:
df=pd.read_csv("/config/workspace/aps_failure_training_set1.csv")
df

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000  ag_001  \
0       pos  153204      0         182     na      0      0      0       0   
1       pos  453236     na        2926     na      0      0      0       0   
2       pos   72504     na        1594   1052      0      0      0     244   
3       pos  762958     na          na     na     na     na    776  281128   
4       pos  695994     na          na     na     na     na      0       0   
...     ...     ...    ...         ...    ...    ...    ...    ...     ...   
36183   neg  153002     na         664    186      0      0      0       0   
36184   neg    2286     na  2130706538    224      0      0      0       0   
36185   neg     112      0  2130706432     18      0      0      0       0   
36186   neg   80292     na  2130706432    494      0      0      0       0   
36187   neg   40222     na         698    628      0      0      0       0   

        ag_002  ...   ee_002   ee_003   ee_004   ee_005   ee_006  ee_007  \
0            0  ...   129862    26872    34044    22472    34362       0   
1          222  ...  7908038  3026002  5025350  2025766  1160638  533834   
2       178226  ...  1432098   372252   527514   358274   332818  284178   
3      2186308  ...       na       na       na       na       na      na   
4            0  ...  1397742   495544   361646    28610     5130     212   
...        ...  ...      ...      ...      ...      ...      ...     ...   
36183        0  ...   998500   566884  1290398  1218244  1019768  717762   
36184        0  ...    10578     6760    21126    68424      136       0   
36185        0  ...      792      386      452      144      146    2622   
36186        0  ...   699352   222654   347378   225724   194440  165070   
36187        0  ...   440066   183200   344546   254068   225148  158304   

       ee_008  ee_009 ef_000 eg_000  
0           0       0      0      0  
1      493800    6914      0      0  
2        3742       0      0      0  
3          na      na     na     na  
4           0       0     na     na  
...       ...     ...    ...    ...  
36183  898642   28588      0      0  
36184       0       0      0      0  
36185       0       0      0      0  
36186  802280  388422      0      0  
36187  170384     158      0      0  

[36188 rows x 171 columns]

In [3]:
df.isnull()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0      False   False   False   False   False   False   False   False   False   
1      False   False   False   False   False   False   False   False   False   
2      False   False   False   False   False   False   False   False   False   
3      False   False   False   False   False   False   False   False   False   
4      False   False   False   False   False   False   False   False   False   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
36183  False   False   False   False   False   False   False   False   False   
36184  False   False   False   False   False   False   False   False   False   
36185  False   False   False   False   False   False   False   False   False   
36186  False   False   False   False   False   False   False   False   False   
36187  False   False   False   False   False   False   False   False   False   

       ag_002  ...  ee_002  ee_003  ee_004  ee_005  ee_006  ee_007  ee_008  \
0       False  ...   False   False   False   False   False   False   False   
1       False  ...   False   False   False   False   False   False   False   
2       False  ...   False   False   False   False   False   False   False   
3       False  ...   False   False   False   False   False   False   False   
4       False  ...   False   False   False   False   False   False   False   
...       ...  ...     ...     ...     ...     ...     ...     ...     ...   
36183   False  ...   False   False   False   False   False   False   False   
36184   False  ...   False   False   False   False   False   False   False   
36185   False  ...   False   False   False   False   False   False   False   
36186   False  ...   False   False   False   False   False   False   False   
36187   False  ...   False   False   False   False   False   False   False   

       ee_009  ef_000  eg_000  
0       False   False   False  
1       False   False   False  
2       False   False   False  
3       False   False   False  
4       False   False   False  
...       ...     ...     ...  
36183   False   False   False  
36184   False   False   False  
36185   False   False   False  
36186   False   False   False  
36187   False   False   False  

[36188 rows x 171 columns]

In [4]:
df.isnull().sum()

class     0
aa_000    0
ab_000    0
ac_000    0
ad_000    0
         ..
ee_007    0
ee_008    0
ee_009    0
ef_000    0
eg_000    0
Length: 171, dtype: int64

In [21]:
null_report=df.isnull().sum()/df.shape[0]
null_report

class     0.0
aa_000    0.0
ab_000    0.0
ac_000    0.0
ad_000    0.0
         ... 
ee_007    0.0
ee_008    0.0
ee_009    0.0
ef_000    0.0
eg_000    0.0
Length: 171, dtype: float64

In [7]:
(df.isnull().sum()/df.shape[0]).values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [16]:
l1=[1,2,3,50,60,80,90,100]
l2=[3,5,6,80.90,100]
for l1_val,l2_val in zip (l1,l2):
    print(l1_val,l2_val)

1 3
2 5
3 6
50 80.9
60 100


In [12]:
for column_name,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)

class 0.0
aa_000 0.0
ab_000 0.0
ac_000 0.0
ad_000 0.0
ae_000 0.0
af_000 0.0
ag_000 0.0
ag_001 0.0
ag_002 0.0
ag_003 0.0
ag_004 0.0
ag_005 0.0
ag_006 0.0
ag_007 0.0
ag_008 0.0
ag_009 0.0
ah_000 0.0
ai_000 0.0
aj_000 0.0
ak_000 0.0
al_000 0.0
am_0 0.0
an_000 0.0
ao_000 0.0
ap_000 0.0
aq_000 0.0
ar_000 0.0
as_000 0.0
at_000 0.0
au_000 0.0
av_000 0.0
ax_000 0.0
ay_000 0.0
ay_001 0.0
ay_002 0.0
ay_003 0.0
ay_004 0.0
ay_005 0.0
ay_006 0.0
ay_007 0.0
ay_008 0.0
ay_009 0.0
az_000 0.0
az_001 0.0
az_002 0.0
az_003 0.0
az_004 0.0
az_005 0.0
az_006 0.0
az_007 0.0
az_008 0.0
az_009 0.0
ba_000 0.0
ba_001 0.0
ba_002 0.0
ba_003 0.0
ba_004 0.0
ba_005 0.0
ba_006 0.0
ba_007 0.0
ba_008 0.0
ba_009 0.0
bb_000 0.0
bc_000 0.0
bd_000 0.0
be_000 0.0
bf_000 0.0
bg_000 0.0
bh_000 0.0
bi_000 0.0
bj_000 0.0
bk_000 0.0
bl_000 0.0
bm_000 0.0
bn_000 0.0
bo_000 0.0
bp_000 0.0
bq_000 0.0
br_000 0.0
bs_000 0.0
bt_000 0.0
bu_000 0.0
bv_000 0.0
bx_000 0.0
by_000 0.0
bz_000 0.0
ca_000 0.0
cb_000 0.0
cc_000 0.0
cd_000 0.0
ce

In [17]:
drop_columns_name=[]
for column_name,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)
    if missing_percentage>0.30:
        drop_columns_name.append(column_name)

class 0.0
aa_000 0.0
ab_000 0.0
ac_000 0.0
ad_000 0.0
ae_000 0.0
af_000 0.0
ag_000 0.0
ag_001 0.0
ag_002 0.0
ag_003 0.0
ag_004 0.0
ag_005 0.0
ag_006 0.0
ag_007 0.0
ag_008 0.0
ag_009 0.0
ah_000 0.0
ai_000 0.0
aj_000 0.0
ak_000 0.0
al_000 0.0
am_0 0.0
an_000 0.0
ao_000 0.0
ap_000 0.0
aq_000 0.0
ar_000 0.0
as_000 0.0
at_000 0.0
au_000 0.0
av_000 0.0
ax_000 0.0
ay_000 0.0
ay_001 0.0
ay_002 0.0
ay_003 0.0
ay_004 0.0
ay_005 0.0
ay_006 0.0
ay_007 0.0
ay_008 0.0
ay_009 0.0
az_000 0.0
az_001 0.0
az_002 0.0
az_003 0.0
az_004 0.0
az_005 0.0
az_006 0.0
az_007 0.0
az_008 0.0
az_009 0.0
ba_000 0.0
ba_001 0.0
ba_002 0.0
ba_003 0.0
ba_004 0.0
ba_005 0.0
ba_006 0.0
ba_007 0.0
ba_008 0.0
ba_009 0.0
bb_000 0.0
bc_000 0.0
bd_000 0.0
be_000 0.0
bf_000 0.0
bg_000 0.0
bh_000 0.0
bi_000 0.0
bj_000 0.0
bk_000 0.0
bl_000 0.0
bm_000 0.0
bn_000 0.0
bo_000 0.0
bp_000 0.0
bq_000 0.0
br_000 0.0
bs_000 0.0
bt_000 0.0
bu_000 0.0
bv_000 0.0
bx_000 0.0
by_000 0.0
bz_000 0.0
ca_000 0.0
cb_000 0.0
cc_000 0.0
cd_000 0.0
ce

In [20]:
drop_columns_name

[]

In [23]:
null_report[null_report>0.03].index

Index([], dtype='object')

In [28]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)

0